apiVersion: v1
kind: Pod
metadata:
  name: inat-pod
  labels:
    k8s-app: inat-app
spec:
  containers:
  - name: shiny
    image: ghcr.io/boettiger-lab/nautilus-shiny
    imagePullPolicy: Always
    env:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: aws-access-key-id
          key: AWS_ACCESS_KEY_ID  
    - name: AWS_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: aws-secret-access-key
          key: AWS_SECRET_ACCESS_KEY
    - name: AWS_S3_ENDPOINT
      value: "rook-ceph-rgw-nautiluss3.rook"
    - name: AWS_PUBLIC_ENDPOINT
      value: "s3-west.nrp-nautilus.io"
    - name: AWS_HTTPS
      value: "false"
    resources:
      requests:
        cpu: 4
        memory: 4Gi
      limits:
        cpu: 4
        memory: 4Gi
